In [ ]:
# Téncnica One-hot encoding
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

doc = "Me gusta el Deep Learning"
doc = doc.lower()
doc = doc.split()
values = array(doc)
print(values)

# 1. Convertir las palabras en tokens y obtener su valor numérico
# de la posición utilizando LabelEncoder()
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

# 2. Obtener la codificación one-hot de la palabra utilizando OneHotEncoder()

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['me' 'gusta' 'el' 'deep' 'learning']
[4 2 1 0 3]
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# Embedding layer de Keras
layers.Embedding(input_dim=vocab_size,
                 output_dim=embedding_dim)

In [18]:
# EJEMPLO: Character-Level Language Model por Andrej Karpathy
# Consiste en darle a la RNN una palabra, entonces se le pide que modele
# la distribución de probabilidad del siguiente carácter que le correspondería
# a la secuencia de caracteres anterores.
from google.colab import drive
drive.mount('/content/drive')
!ls
path_to_fileDL = '/content/drive/MyDrive/Antología-literaria-1.txt'
text = open(path_to_fileDL, 'rb').read().decode(encoding='utf-8')
print('Longitud del texto: {} carácteres'.format(len(text)))
vocab = sorted(set(text))
print('El texto está compuesto de esto {} carácteres:'.format(len(vocab)))
print(vocab)
#Como estamos tratando el caso de estudio a nivel de carácter, podríamos considerar
# que aquí el corpus son los caracteres y, por tanto, sería un corpus muy pequeño.


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
drive  sample_data  training_checkpoints
Longitud del texto: 249659 carácteres
El texto está compuesto de esto 111 carácteres:
['\t', '\n', '\x0c', ' ', '!', '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '¡', '©', '«', '\xad', '´', 'º', '»', '¿', 'Á', 'É', 'Í', 'Ñ', 'Ó', 'Ú', 'á', 'é', 'í', 'ñ', 'ó', 'ú', 'ü', '–', '—', '’', '“', '”', '•', '…']


In [19]:
# Las redes neuronales solo procesan valores numéricos, no letras
import tensorflow as tf
from tensorflow import keras
import numpy as np
from numpy import array

char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)

# Ahora tenemos un token con la representación de entero (integer) para
# cada carácter, como podemos ver ejecutando el siguiente código
for char,_ in zip(char2idx, range(len(vocab))):
  print(' {:4s}: {:3d},'.format(repr(char),char2idx[char]))

 '\t':   0,
 '\n':   1,
 '\x0c':   2,
 ' ' :   3,
 '!' :   4,
 '(' :   5,
 ')' :   6,
 '*' :   7,
 ',' :   8,
 '-' :   9,
 '.' :  10,
 '/' :  11,
 '0' :  12,
 '1' :  13,
 '2' :  14,
 '3' :  15,
 '4' :  16,
 '5' :  17,
 '6' :  18,
 '7' :  19,
 '8' :  20,
 '9' :  21,
 ':' :  22,
 ';' :  23,
 '<' :  24,
 '=' :  25,
 '>' :  26,
 '?' :  27,
 'A' :  28,
 'B' :  29,
 'C' :  30,
 'D' :  31,
 'E' :  32,
 'F' :  33,
 'G' :  34,
 'H' :  35,
 'I' :  36,
 'J' :  37,
 'K' :  38,
 'L' :  39,
 'M' :  40,
 'N' :  41,
 'O' :  42,
 'P' :  43,
 'Q' :  44,
 'R' :  45,
 'S' :  46,
 'T' :  47,
 'U' :  48,
 'V' :  49,
 'W' :  50,
 'X' :  51,
 'Y' :  52,
 'Z' :  53,
 '[' :  54,
 ']' :  55,
 '_' :  56,
 'a' :  57,
 'b' :  58,
 'c' :  59,
 'd' :  60,
 'e' :  61,
 'f' :  62,
 'g' :  63,
 'h' :  64,
 'i' :  65,
 'j' :  66,
 'k' :  67,
 'l' :  68,
 'm' :  69,
 'n' :  70,
 'o' :  71,
 'p' :  72,
 'q' :  73,
 'r' :  74,
 's' :  75,
 't' :  76,
 'u' :  77,
 'v' :  78,
 'w' :  79,
 'x' :  80,
 'y' :  81,
 'z' :  82,
 '

In [20]:
# Con esta función, inversa a la anterior, podemos pasar el texto (todo el libro) a enteros
text_as_int = np.array([char2idx[c] for c in text])

# Lo comprobaremos mostrando los 50 primeros caracteres del teexto
print('texto: {}'.format(repr(text[:50])))
print('{}'.format(repr(text_as_int[:50])))

texto: 'SECUNDARIA\n\nEscudo Nacional\n\n1\n\nANTOLOGÍA LITERARI'
array([46, 32, 30, 48, 41, 31, 28, 45, 36, 28,  1,  1, 32, 75, 59, 77, 60,
       71,  3, 41, 57, 59, 65, 71, 70, 57, 68,  1,  1, 13,  1,  1, 28, 41,
       47, 42, 39, 42, 34, 93, 28,  3, 39, 36, 47, 32, 45, 28, 45, 36])


In [21]:
# PREPARACIÓN DE LOS DATOS PARA SER USADOS POR LA RNN

# En nuestro ejemplo definios la variable se_lenght = 100
# Significa que dividiremos secuencias de seq_lenght+1 de caracteres
# y las iremos desplazando un caracter a la derecha

# La función tf.data.Dataset from_tensor_slices, crea un conjunto de datos
# con el contenido del tensor text_as_int que contiene el texto, al que podremos
# aplicar el método batch() para divir este conjunnto de datos en secuencias de seq_lenght+1
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
seq_lenght = 100
sequences = char_dataset.batch(seq_lenght+1,drop_remainder=True)

# Comprobamos que sequences contiene el texto dividido en paquetes de 101 caracteres
for item in sequences.take(10):
  print(repr(''.join(idx2char[item.numpy()])))

'SECUNDARIA\n\nEscudo Nacional\n\n1\n\nANTOLOGÍA LITERARIA\n\nSECUNDARIA\n\nISBN 978-612-01-0310-4\n\nBandera Naci'
'onal\n\nAntología\nliteraria\n\n1\n\n\x0cMINISTERIO DE EDUCACIÓN\nDirección de Educación Secundaria\n\nAntología\nl'
'iteraria\n1\n\n1\n\nAntologías 1ro_26JUN.indd 1\n\n22/08/18 9:11\n\n\x0cZ_Antologías Literaria 1ro - Pg02 Credito'
'.pdf\n\n1\n\n14/12/18\n\n10:54\n\nTítulo: Antología literaria 3\nTítulo: Antología literaria 1\nMinisterio de E'
'ducación\nMinisterio\nde Educación\nCalle\nDel Comercio\nN.º 193, San Borja\nCalle Del Comercio N.º 193, Sa'
'n Borja\nLima 41, Perú\nLima 41, Perú\nTeléfono: 615-5800\nTeléfono: 615-5800\nwww.minedu.gob.pe\nwww.mined'
'u.gob.pe\nPrimera edición: 2015\nPrimera edición: 2015\nSegunda edición: junio de 2017\nCuarta reimpresió'
'n: noviembre de 2018\nTiraje: 457 169 ejemplares\nTiraje: 550 824 ejemplares\nCoordinadora\nKaren\nCoral R'
'odríguez\nCoordinadora\nKaren Coral Rodríguez\nAntologadores\nMarco\nBassino Pinasco\nAntologadore

In [22]:
# De esta secuencia se obtiene el conjunto de datos de entrenamiento
# Se crea la función que divide los datos de entrada (0 al 99) de los de
# salida (1 al 100)

def split_input_target(chunk):
  input_text = chunk[:-1]
  target_text = chunk[1:]
  return input_text, target_text
dataset = sequences.map(split_input_target)

# Se puede comprobar así
for input_example, target_example in dataset.take(1):
  print('Input data:',
        repr(''.join(idx2char[input_example.numpy()])))
  print('Target data:',
        repr(''.join(idx2char[target_example.numpy()])))


Input data: 'SECUNDARIA\n\nEscudo Nacional\n\n1\n\nANTOLOGÍA LITERARIA\n\nSECUNDARIA\n\nISBN 978-612-01-0310-4\n\nBandera Nac'
Target data: 'ECUNDARIA\n\nEscudo Nacional\n\n1\n\nANTOLOGÍA LITERARIA\n\nSECUNDARIA\n\nISBN 978-612-01-0310-4\n\nBandera Naci'


In [23]:
# En este punto, disponemos de los datos de entrenamiento en el tensor dataset
# en forma de parejas de secuencias de 100 integers de 64 bits que representan
# un carácter del vocabulario
print(dataset)

<_MapDataset element_spec=(TensorSpec(shape=(100,), dtype=tf.int64, name=None), TensorSpec(shape=(100,), dtype=tf.int64, name=None))>


In [24]:
# Los datos ya están preprocesados en el formato que se requiere para ser usados
# en el entreno de la red, pero recordemos que estos deben de ser agruapdos en
# batches antes de pasarlos al modelo.
# Se utilizará la función tf.data, que también eprmite barajar las secuencias previamente

BATCH_SIZE = 64
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)
print(dataset)

# Es así que tenemos batches compuestos de 64 parejas de secuencias de 100 integers
# de 64 bits que representan el carácter correspondiente del vocabulario


<_BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>


In [25]:
# CONSTRUCCIÓN DEL MODELO RNN
# Usaremos una versión mínima de RNN para facilitar la explicación, que contega
# solo una capa LSTM.
# En concreto, definimos uan red de solo 3 capas

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

def build_model(vocab_size, embedding_dim,rnn_units,batch_size):
  model=Sequential()
  model.add(Embedding(input_dim=vocab_size,
                      output_dim=embedding_dim,
                      batch_input_shape=[batch_size,None]))
  model.add(LSTM(rnn_units,
                 return_sequences=True,
                 stateful=True,
                 recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  return model

vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

model = build_model(
   vocab_size = vocab_size,
   embedding_dim = embedding_dim,
   rnn_units=rnn_units,
   batch_size=BATCH_SIZE
)

# La primera capa es de tipo word embedding, que mapea cada carácter de entrada
# en un vector ambedding. Esta capa permite especificar varios argumentos:
# 1. Tamaño del vocabulario, que indica cuántos vectores embedding tendrá la capa
# 2. Dimensiones de estos vectores embedding, que son 256
# 3. Tamaño del batch, que es de 64

# La segunda capa es de tipo LSTM. rnn_units indica el número de neuronas recurrentes
# Con return_sequence se indica si queremos predecir el carácter siguiente a
# todos los caracteres de entrada, no solo al último carácter.
# El argumento stateful indica, el uso de las capacidades de memoria de la red
# entre batches. Si es False: cada nuevo batch se inicializan las memory cell.
# Si es False, para chada batch se mantendrán las actualizaciones hechas durante
# la ejecuación del batch anterior
# Recurrente_kernel inidca cómo deben inicializar los pesos de las matrices internas
# de la red. En este caso usamos la distribución uniforme glorot_uniform, habitual
# en estos casos.

# La última capa es de tipo Dense. El argumento units nos dice cuántas neuronas
# tendrá la capa y que nos marcará la dimensión de la salida. En este caso será
# igual al tamaño de nuestro vocabulario (vocab_size)

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (64, None, 256)           28416     
                                                                 
 lstm_2 (LSTM)               (64, None, 1024)          5246976   
                                                                 
 dense_2 (Dense)             (64, None, 111)           113775    
                                                                 
Total params: 5,389,167
Trainable params: 5,389,167
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Inspeccionamos las dimensiones de los tensores para poder comprender más
# a fondo el modelo.
for input_example_batch, target_example_batch in dataset.take(1):
  print("Input:", input_example_batch.shape, "#(batch_size, sequence_lenght)")
  print("Target:",target_example_batch.shape, "#(batch_size, sequence_lenght)")

# Vemos que en esta red la secuencia de entrada son batches de 100 caracteres, pero
# el modelo una vez entrenado puede ser ejecutado con cualquier tamaño de cadena
# de entrada.
# Como salida, el modelo nos devuelve un tensor con una dimensión adicional con
# la verosimilitud para cada carácter del vocabulario:

for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print("Prediction: ", example_batch_predictions.shape,
        "#(batch_size, sequence_lenght, vocab_size)")

# La capa Densa de esta red no tiene una función de activación softmax, es por eso
# que retorna el vector con un indicador de "evidencia" para cada carácter

Input: (64, 100) #(batch_size, sequence_lenght)
Target: (64, 100) #(batch_size, sequence_lenght)
Prediction:  (64, 100, 111) #(batch_size, sequence_lenght, vocab_size)


In [27]:
# El siguiente paso es elegir uno de los caracteres. No se elige el más probable,
# porque puede entrar en un bucle. Se obtiene una muestra de la distribución de salida

# Se prueba para el primer ejjemplo en el batch
sampled_indices = tf.random.categorical(
    example_batch_predictions[0],
    num_samples=1)
sampled_indices_characters = tf.squeeze(
    sampled_indices,axis=-1).numpy()
print(sampled_indices_characters)

# Con tf.random.categorical se obtiene una muestra de una distibución categórica
# y con squeeze se eliminan las dimensiones del tensor de tamaño 1. Así, en cada
# instante de tiempo se obtiene una predicción del índice del siguiente carácter.


[ 86  38  54   0  66  91  73  73   9  95  67  48  34  28  98  40  67  20
  48  84  81   2  93  40  72  62  17  41  48  12  56  94  87  37  90  36
  60  17  12  16  96  43  80  62   9  29  95  47  71 102  26  87  76  80
  57  84  59  62  24  15  39  46  67  93  59  64  28   3  65  41  30  86
  71  70  22  25  62  45  97  31  33  50  66  59  70  87  29  84  61  59
 108  68  19  18   6 100  61  14   9  77]


In [28]:
# ENTRENAMIENTO DEL MODELO RNN
# Para la función de pérdida usaremos al función estándar tf.leras.losses.sparse_categorcial_crossentropy,
# pues se trata de datos categóricos. Dado que el retorno se trata de valores de
# verosimilitud (no de probabilidades) se instanciará el argumento from_logits a True

def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(
      labels,logits,from_logits=True)

# En cuanto al optimizador, se usará el Adam con argumentos por defecto
model.compile(optimizer='adam', loss=loss)

In [29]:
# Se aprovecharán los Checkpoints, una técnica de tolerancia de fallos para
# procesos cuyo tiempo de ejecución es muy largo.
# La librería de Keras proporciona Checkpoints a través de la API Callbacks.
# Se debe especificar el directorio en el que se guardarán los Checkpoints y
# el nombre del fichero

import os
checkpoint_dir = './training_checkpoints'
checkpoint_prefix=os.path.join(checkpoint_dir,"ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                                       save_weights_only=True)

In [30]:
EPOCHS=50
history=model.fit(dataset,
                  epochs=EPOCHS,
                  callbacks=[checkpoint_callback])

!ls training_checkpoints

Epoch 1/50
38/38 [==============================] - 7s 113ms/step - loss: 3.3715
Epoch 2/50
38/38 [==============================] - 4s 81ms/step - loss: 2.8273
Epoch 3/50
38/38 [==============================] - 4s 78ms/step - loss: 2.4191
Epoch 4/50
38/38 [==============================] - 3s 73ms/step - loss: 2.2600
Epoch 5/50
38/38 [==============================] - 3s 70ms/step - loss: 2.1549
Epoch 6/50
38/38 [==============================] - 3s 79ms/step - loss: 2.0800
Epoch 7/50
38/38 [==============================] - 3s 77ms/step - loss: 2.0065
Epoch 8/50
38/38 [==============================] - 3s 71ms/step - loss: 1.9449
Epoch 9/50
38/38 [==============================] - 3s 80ms/step - loss: 1.8890
Epoch 10/50
38/38 [==============================] - 4s 89ms/step - loss: 1.8327
Epoch 11/50
38/38 [==============================] - 3s 73ms/step - loss: 1.7770
Epoch 12/50
38/38 [==============================] - 3s 77ms/step - loss: 1.7212
Epoch 13/50
38/38 [=================

In [31]:
# GENERACIÓN DE TEXTO CON EL MODELO

tf.train.latest_checkpoint(checkpoint_dir)

# Para mantenerlo simplle, se usará un tamaño de batch de 1.
# El modelo solo acepta un tamaño de batch fijo una vez construido, así que se
# necesita reconstruir manualmente el modelo con el método build() y restaurar sus
# pesos desde el Checkpoint
model=build_model(vocab_size, embedding_dim,
                  rnn_units,batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1,None]))


In [32]:
def generate_text(model,start_string):

  num_generate=500 #Número de caracteres a predecir
  input_eval=[char2idx[s] for s in start_string] # start_string covierte la palabra
  # a su corresondiente representación numérica
  # Se preparan los tensores ncesarios
  input_eval = tf.expand_dims(input_eval,0)
  text_generated=[]

  # Se usa la variabel temperatura para decir cuán observador en sus predicciones
  # queremos que sea nuestro modelo.
  # Con temperaturas altas (hasta 1) hay más creatividad pero con más errores.
  # Con temperaturas bajas habrá menos errores pero poca creatividad.
  temperature=0.5

  model.reset_states()
  # Comienza el bucle para generar los caracteres que le hemos indicado
  for i in range(num_generate):
    predictions=model(input_eval)
    # Trabajamos con un batch tamaño 1, pero el modelo retorna el tensor del batch
    # con las dimensiones con que lo habíamos entrenado, hay que reducirlo
    predictions = tf.squeeze(predictions,0)
    # Se una distribución categórica para calcular el índice del carácter predicho
    predictions = predictions/temperature
    predicted_id=tf.random.categorical(predictions,
                                       num_samples=1)[-1,0].numpy()
    # Este carácter acabadod e predecir se usa como nuestra próxima entrada al modelo,
    # retroalimentando para que ahora tenga más contexto.
    input_eval = tf.expand_dims([predicted_id],0)

    text_generated.append(idx2char[predicted_id])

  return (start_string + ''.join(text_generated))

In [16]:
# Probemos con una palabra que no conoce el modelo
print(generate_text(model, start_string= u"domingo"))

domingo (ver Figura 6.8) con el que estos parámetros de ambas redes,
presentando algunas de las capas del modelo en cada epoch se implementado en el capítulo 13 antes de acabar es el carácter introductorio del libro entraremos en detalle en el hardware disponible en:
https://en.wikipedia.org/wiki/RGB [Consultado: 12/12/2019].



51 Véase https://keras.io/layers/core/#dense [Consulta:
16/12/2019].



99 Véase https://keras.io/callbacks/ [Consultado:
12/12/2019].



51 Véase https://www.k


In [33]:
# Probemos con una palabra que sí conoce
print(generate_text(model, start_string= u"Ella"))

Ellas fastras, y cuando el joven le hacía alguna observación, contestó un adilla por brazos yo como lo amargo! ¡Ese dio peo?
—¡Est Kués con ellas y sus fracasos.
Un mundo de emociones y sentimientos. Alguien decuento conciendo las cabezas de los
lwas murales en la cabeza.
—No, él no es eso. Es bueno oprendió es pero el muchachito de dinero para comportar la puerta.
—¿Quién la había llevado en seguida. Pero tendrías que es rediatar tú.
—Yo soy el colonel…
—¡No! ¡Es tungo nueve abrirtada. ¡De ninguna 
