In [1]:
import tensorflow as tf
print("GPU: Available: ", tf.test.is_gpu_available())
print(tf.__version__)
from tensorflow import keras
#print(tf.keras.__version__)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


GPU: Available:  True
2.13.0


In [2]:
import numpy as np
# Keras usa un array multidimensional de NumPy como estructura básica
# de datos, y llama a esta estructura de datos <<Tensor>>.

# ==============
# === Tensor ===
# ==============
# Tiene tres atributos principales:
#     - Número de ejes
#     - Forma
#     - Tipo de datos


x=np.array([1,2,3,4,5.5])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:  [1.  2.  3.  4.  5.5]
x ndim:  1
x shape:  (5,)
x size:  5
x dtype:  float64


In [7]:
# Tensor 2D
x = np.array([[2,4,6,8],[1,2,3,4]])
print(f'x: {x}')
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x: [[2 4 6 8]
 [1 2 3 4]]
x ndim:  2
x shape:  (2, 4)
x size:  8
x dtype:  int64


In [9]:
# Tensor 3D
x = np.array([[[1,2,3,4],[5,6,7,8]], [[2,4,6,8],[10,12,14,16]]])
print("x:\n",x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x dtype: ", x.dtype)
print("x size: ", x.size)


x:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 2  4  6  8]
  [10 12 14 16]]]
x ndim:  3
x shape:  (2, 2, 4)
x dtype:  int64
x size:  16


In [12]:
# Crear tensores rápidamente
print("np.zeros((3,3)): \n", np.zeros((3,3)))
print("np.ones((3,3)):\n", np.ones((3,3)))
print("np.eye((3,3)):\n", np.eye((3)))
print("np.random.random((3,3)):\n",np.random.random((3,3)))

np.zeros((3,3)): 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye((3,3)):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random((3,3)):
 [[0.82145299 0.1577081  0.90136739]
 [0.3249681  0.9807291  0.15885156]
 [0.64444836 0.80327439 0.70203878]]


In [21]:
# --- Manipulación de tensores ---
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print("x column 1:",x[:,1])
print("x row 0:", x[0,:])
print("x rows 0,1 & cols 1,2: \n", x[0:2,1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1: [ 2  6 10]
x row 0: [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [23]:
# Producto punto de matrices

a = np.array([[1,2,3],[4,5,6]],dtype=np.int32)
b = np.array([[7,8],[9,10],[11,12]], dtype=np.int32)
c = a.dot(b)
print(f'{a.shape}.{b.shape} = {c.shape}')
print(c)

(2, 3).(3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


In [25]:
# Cambiar forma de tensores
x = np.array([[1,2,3,4,5,6]])
print(x)
y = x.reshape(2,3)
print("y:\n",y)
print("y.shape: ", y.shape)
z = np.reshape(x,(2,-1))
print("z:\n",z)
print("z shape: ", z.shape)

[[1 2 3 4 5 6]]
y:
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z:
 [[1 2 3]
 [4 5 6]]
z shape:  (2, 3)


In [34]:
#Añadir dimensión a un tensor
x=np.array([[1,2,3],[4,5,6]])
print("x:\n", x)
print("x.shape: ", x.shape)
y = np.expand_dims(x,1)
print("y:\n", y)
print("y.shape: ",y.shape)

#Borrar dimensión a un tensor
z=np.squeeze(y,1)
print("z:\n",z)
print("z.shape: ",z.shape)


x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)
z:
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [ ]:
# Valor máximo en un tensor
#argmax devuelve el índice del valor máximo a lo largo de un eje de un tensor
x = np.array([1,2,3,4])
print(x)
print(np.argmax(x))
print(np.max(x))


[1 2 3 4]
3
4


In [ ]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print (np.argmax(x))
print (np.max(x))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
12


# Nueva sección

In [ ]:
# Se puede especificar el eje
# El índice 2 de cada columna
# Si es axis=1 sería el índice de cada fila
print(np.argmax(x,axis=0))
print(np.max(x,axis=0))

[2 2 2 2]
[ 9 10 11 12]
